### ISSUE TITLE
After sunset working date changes, how to override

### ISSUE THREAD

**Issue by IsraelDev** [MosheBerman/KosherCocoa#138] opened 2019-01-21 20:26 UTC
The function `KCJewishCalendar workingDateAdjustedForSunset` always runs even when I pass in a different date. Sometimes I don't want the day after, even if it's after sunset, how do I override?

**Comment by Elyahu41** [comment] 2023-03-21 22:03
Just edit the method to not use workingDateAdjustedForSunset and to use workingDate instead.

**Comment by MosheBerman** [comment] 2023-12-28 21:49
Duplicate of #142, addressed in PR #156

**Closed by MosheBerman** 2023-12-28 21:49 UTC
